2020-10-05 13:43:38,229 ERROR: Exception on /explore [GET] [in /Users/dhyungseoklee/Projects/Flask/virtual_env/flask_env/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/dhyungseoklee/Projects/Flask/virtual_env/flask_env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dhyungseoklee/Projects/Flask/virtual_env/flask_env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dhyungseoklee/Projects/Flask/virtual_env/flask_env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dhyungseoklee/Projects/Flask/virtual_env/flask_env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/dhyungseoklee/Projects/Flask/virtual_env/flask_env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dhyungseoklee/Projects/Flask/virtual_env/flask_env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/dhyungseoklee/Projects/Flask/virtual_env/flask_env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/dhyungseoklee/Projects/Flask/microblog/app/routes.py", line 149, in explore
    return render_template('index.html', title = 'Explore', posts=posts)
  File "/Users/dhyungseoklee/Projects/Flask/virtual_env/flask_env/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/dhyungseoklee/Projects/Flask/virtual_env/flask_env/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/dhyungseoklee/Projects/Flask/virtual_env/flask_env/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/dhyungseoklee/Projects/Flask/virtual_env/flask_env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/dhyungseoklee/Projects/Flask/virtual_env/flask_env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/dhyungseoklee/Projects/Flask/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/dhyungseoklee/Projects/Flask/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/dhyungseoklee/Projects/Flask/microblog/app/templates/index.html", line 18, in block "content"
    {% include '_post.html' %}
  File "/Users/dhyungseoklee/Projects/Flask/microblog/app/templates/_post.html", line 3, in top-level template code
    <td><img src="{{ post.author.avatar(36) }}"></td>
  File "/Users/dhyungseoklee/Projects/Flask/virtual_env/flask_env/lib/python3.7/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'post' is undefined
2020-10-05 13:45:25,802 INFO: Microblog startup [in /Users/dhyungseoklee/Projects/Flask/microblog/app/__init__.py:43]
2020-10-05 14:48:21,326 INFO: Microblog startup [in /Users/dhyungseoklee/Projects/Flask/microblog/app/__init__.py:43]
